# Generated by Django 3.2.10 on 2023-03-11 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, max_length=11)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2023, 3, 11, 9, 13, 58, 674127))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2023, 3, 11, 9, 13, 58, 674127))),
            ],
            options={
                'db_table': 'Counters',
            },
        ),
        migrations.CreateModel(
            name='datasmodel',
            fields=[
                ('id', models.CharField(db_index=True, max_length=128, primary_key=True, serialize=False, verbose_name='序号')),
                ('nickName', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信名')),
                ('avatarUrl', models.CharField(blank=True, max_length=200, null=True, verbose_name='头像链接')),
                ('_e8549b99_d7ea_3464_bc63_4ba2dcc23b51', models.TextField(blank=True, null=True, verbose_name='性别')),
                ('_05a53093_58e6_39b1_a837_02f3f663009f', models.TextField(blank=True, null=True, verbose_name='年龄')),
                ('_4359099b_358d_3585_a012_d975a6cf2abd', models.TextField(blank=True, null=True, verbose_name='居住区域')),
                ('_0c929b5a_8e29_34da_8c61_3704437d8c16', models.TextField(blank=True, null=True, verbose_name='居住时间')),
                ('_c3fbe1d4_2042_3425_a3c8_02ad8e7a670f', models.TextField(blank=True, null=True, verbose_name='月收入')),
                ('_634f177c_4ebc_36da_81c0_e2e82a7737db', models.TextField(blank=True, null=True, verbose_name='文化程度')),
                ('_f4073b8e_d8d5_35c9_8727_3e2a2a88c0c5', models.TextField(blank=True, null=True, verbose_name='职业')),
                ('_f7404e95_9d18_3664_967f_ce709a4e8317', models.TextField(blank=True, null=True, verbose_name='最具有精神价值的地方')),
                ('_1cba0acb_7071_3ecc_b703_9612ffd2c404', models.TextField(blank=True, null=True, verbose_name='最具有休闲娱乐价值的地方')),
                ('_d9dfc62a_9761_3540_9e4c_7f88536361ca', models.TextField(blank=True, null=True, verbose_name='最具有美学价值的地方')),
                ('_99cfff26_fb91_307a_af20_601c5957eb0d', models.TextField(blank=True, null=True, verbose_name='最具有地方感的地方')),
                ('_14d8d11b_d640_35ff_93de_abd4f246d172', models.TextField(blank=True, null=True, verbose_name='最具有社会关系价值的地方')),
                ('_fe0254d2_b85e_3c8b_9faf_f892b31c528d', models.TextField(blank=True, null=True, verbose_name='最具有文化遗产价值的地方')),
                ('_854c1c71_483f_30c5_8e3e_f3766309b292', models.TextField(blank=True, null=True, verbose_name='最具有教育价值的地方')),
                ('_26870961_e853_372f_9048_feebda2d3bcb', models.TextField(blank=True, null=True, verbose_name='让您产生不愉快心理的地方')),
                ('_c9a6bff6_9167_3d57_8215_4971b9f62883', models.TextField(blank=True, null=True, verbose_name='让您感到不安全的地方')),
                ('_efe660d8_9d5e_3d77_9bed_13d882685acf', models.TextField(blank=True, null=True, verbose_name='让您感到不安全的地方')),
                ('_136e6862_a481_37a0_910a_02fdd998c633', models.TextField(blank=True, null=True, verbose_name='精神价值方面')),
                ('_586837ae_ca05_35e6_81ca_2d131dbe363c', models.TextField(blank=True, null=True, verbose_name='休闲娱乐价值')),
                ('_0ac9ba39_22ea_3707_a727_6cf6d68cbcae', models.TextField(blank=True, null=True, verbose_name='美学价值')),
                ('_f93ff9e0_33f7_312b_8f76_51419d9e83bc', models.TextField(blank=True, null=True, verbose_name='地方感价值')),
                ('_76ef99fd_225d_3bb2_84df_3c604cf35380', models.TextField(blank=True, null=True, verbose_name='社会关系价值')),
                ('_223d79fd_0454_3c87_a74e_b562759f7e1a', models.TextField(blank=True, null=True, verbose_name='文化遗产价值')),
                ('_7df178f5_74fb_365d_b557_ca12fbfbcb6c', models.TextField(blank=True, null=True, verbose_name='教育价值')),
            ],
            options={
                'verbose_name': '信息详情',
                'verbose_name_plural': '信息列表',
            },
        ),
    ]
